"""initial — Phase A1 tables (users, user_sessions, audit_log, inference_routing_log)

Revision ID: 0001
Revises:
Create Date: 2026-05-07

This migration establishes the foundational schema per docs/db-schema.md and
PRD §5.1, §5.3. It is hand-written rather than autogenerated so the partial
indexes, CHECK constraints, and trigger function are exactly as the schema
doc specifies.

Notes:
- pgcrypto extension is enabled for gen_random_uuid() (UUID v4). Per
  docs/db-schema.md, UUID v7 is preferred but v4 is acceptable; we go with
  v4 to avoid a third-party extension dependency in v1.
- citext extension is enabled for the case-insensitive users.email column.
- The set_updated_at() trigger function is created here and attached to
  the users table. Future entity tables that need updated_at will reuse it.
- inference_routing_log.chat_id and message_id are columns without FK
  constraints — those columns reference tables (chats, messages) that
  don't exist until Task C3. A future migration will ALTER TABLE to add
  the FK constraints once those tables exist.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ------------------------------------------------------------------
    # Extensions
    # ------------------------------------------------------------------
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ------------------------------------------------------------------
    # Helper: trigger function to maintain updated_at on UPDATE
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    # ------------------------------------------------------------------
    # users
    # ------------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("email", postgresql.CITEXT(), nullable=False, unique=True),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("hashed_password", sa.Text(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("totp_secret", sa.Text(), nullable=True),
        sa.Column("recovery_codes", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deletion_scheduled_at", sa.DateTime(timezone=True), nullable=True),
    )

    # Partial index: active users by email (unique-by-construction via the
    # unique constraint above; this index narrows lookups to non-deleted rows)
    op.execute(
        """
        CREATE INDEX idx_users_email_active
            ON users (email)
            WHERE deleted_at IS NULL
        """
    )
    op.execute(
        """
        CREATE INDEX idx_users_deletion_scheduled
            ON users (deletion_scheduled_at)
            WHERE deletion_scheduled_at IS NOT NULL
        """
    )

    # updated_at trigger
    op.execute(
        """
        CREATE TRIGGER trg_users_set_updated_at
            BEFORE UPDATE ON users
            FOR EACH ROW
            EXECUTE FUNCTION set_updated_at()
        """
    )

    # ------------------------------------------------------------------
    # user_sessions
    # ------------------------------------------------------------------
    op.create_table(
        "user_sessions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE", name="fk_user_sessions_user_id"),
            nullable=False,
        ),
        sa.Column("refresh_token_hash", sa.Text(), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.create_index("idx_user_sessions_user_id", "user_sessions", ["user_id"])
    op.execute(
        """
        CREATE INDEX idx_user_sessions_token_hash
            ON user_sessions (refresh_token_hash)
            WHERE revoked_at IS NULL
        """
    )
    op.create_index("idx_user_sessions_expires", "user_sessions", ["expires_at"])

    # ------------------------------------------------------------------
    # audit_log (PRD §5.3 — privilege fields are first-class)
    # ------------------------------------------------------------------
    op.create_table(
        "audit_log",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL", name="fk_audit_log_user_id"),
            nullable=True,
        ),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("resource_type", sa.Text(), nullable=False),
        sa.Column("resource_id", sa.Text(), nullable=True),
        sa.Column(
            "privilege_marked", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column("privilege_basis", sa.Text(), nullable=True),
        sa.Column("routed_inference_tier", sa.SmallInteger(), nullable=True),
        sa.Column("routed_provider", sa.Text(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column("details", postgresql.JSONB(), nullable=True),
        sa.CheckConstraint(
            "routed_inference_tier IS NULL OR (routed_inference_tier BETWEEN 1 AND 5)",
            name="chk_audit_log_tier_range",
        ),
        sa.CheckConstraint(
            "NOT privilege_marked OR privilege_basis IS NOT NULL",
            name="chk_audit_log_privileged_with_basis",
        ),
    )

    op.execute("CREATE INDEX idx_audit_log_timestamp ON audit_log (timestamp DESC)")
    op.execute("CREATE INDEX idx_audit_log_user_timestamp ON audit_log (user_id, timestamp DESC)")
    op.execute("CREATE INDEX idx_audit_log_resource ON audit_log (resource_type, resource_id)")
    op.execute(
        """
        CREATE INDEX idx_audit_log_privileged
            ON audit_log (privilege_marked, timestamp DESC)
            WHERE privilege_marked = TRUE
        """
    )
    op.execute(
        """
        CREATE INDEX idx_audit_log_tier
            ON audit_log (routed_inference_tier, timestamp DESC)
            WHERE routed_inference_tier IS NOT NULL
        """
    )

    # ------------------------------------------------------------------
    # inference_routing_log (PRD §3.13, §1.5.2 — Tier Derivation choke point)
    # ------------------------------------------------------------------
    op.create_table(
        "inference_routing_log",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL", name="fk_inference_log_user_id"),
            nullable=True,
        ),
        # FK to chats(id) and messages(id) added in a later migration once
        # those tables exist (Task C3). For now: plain UUID columns.
        sa.Column("chat_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("message_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("requested_model", sa.Text(), nullable=True),
        sa.Column("routed_provider", sa.Text(), nullable=False),
        sa.Column("routed_model", sa.Text(), nullable=False),
        sa.Column("routed_inference_tier", sa.SmallInteger(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("cost_estimate", sa.Numeric(10, 4), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "anonymization_applied",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column("refused", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("refusal_reason", sa.Text(), nullable=True),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "routed_inference_tier BETWEEN 1 AND 5",
            name="chk_inference_log_tier_range",
        ),
    )

    op.execute("CREATE INDEX idx_inference_log_timestamp ON inference_routing_log (timestamp DESC)")
    op.execute(
        """
        CREATE INDEX idx_inference_log_user
            ON inference_routing_log (user_id, timestamp DESC)
            WHERE user_id IS NOT NULL
        """
    )
    op.execute(
        """
        CREATE INDEX idx_inference_log_tier_time
            ON inference_routing_log (routed_inference_tier, timestamp DESC)
        """
    )
    op.execute(
        """
        CREATE INDEX idx_inference_log_provider_time
            ON inference_routing_log (routed_provider, timestamp DESC)
        """
    )
    op.execute(
        """
        CREATE INDEX idx_inference_log_refused
            ON inference_routing_log (timestamp DESC)
            WHERE refused = TRUE
        """
    )


def downgrade() -> None:
    # Drop in reverse FK-dependency order
    op.drop_table("inference_routing_log")
    op.drop_table("audit_log")
    op.drop_table("user_sessions")

    # Trigger goes with its table; drop trigger before table to be explicit
    op.execute("DROP TRIGGER IF EXISTS trg_users_set_updated_at ON users")
    op.drop_table("users")

    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")

    # Extensions: leave citext and pgcrypto alone — other apps in the cluster
    # may rely on them. Dropping them in a migration is generally undesirable.
