apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lq-ai.fullname" . }}-gateway
  labels:
    {{- include "lq-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
data:
  gateway.yaml: |-
{{ .Values.gateway.config | indent 4 }}
