apiVersion: v1
kind: Service
metadata:
  name: {{ include "lq-ai.fullname" . }}-postgres
  labels:
    {{- include "lq-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      name: postgres
  selector:
    {{- include "lq-ai.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
