apiVersion: v1
kind: Service
metadata:
  name: {{ include "lq-ai.fullname" . }}-api
  labels:
    {{- include "lq-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      name: http
  selector:
    {{- include "lq-ai.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
